generatorName: dart-network
pubName: my_api_client
pubVersion: 1.0.0
pubDescription: "A generated API client using dart_network_layer_core"

# The additionalProperties section is where custom variables are passed to the codegen
additionalProperties:
  # Using the newly added parameter
  dartNetworkLayerVersion: "^1.0.0-dev.10"

  # You can also specify the serialization library if needed
  serializationLibrary: "json_serializable"

